export const sampleProducts = [
	{
		'Product code': '001234',
		'Product name': 'YOLO',
		'Product link': '',
		Category: 'Fluids',
		Collection: 'YOLO',
		Axis: 'Makeup',
		'Image URL': '',
		'Product Variant Code': '',
	},
	{
		'Product code': '001235',
		'Product name': 'YOLO 0,5N',
		'Product link': '',
		Category: 'Fluids',
		Collection: 'YOLO',
		Axis: 'Makeup',
		'Image URL': '',
		'Product Variant Code': '001234',
	},
	{
		'Product code': '001236',
		'Product name': 'YOLO 00',
		'Product link': '',
		Category: 'Fluids',
		Collection: 'YOLO',
		Axis: 'Makeup',
		'Image URL': '',
		'Product Variant Code': '001234',
	},
	{
		'Product code': '001237',
		'Product name': 'YOLO 0N',
		'Product link': '',
		Category: 'Fluids',
		Collection: 'YOLO',
		Axis: 'Makeup',
		'Image URL': '',
		'Product Variant Code': '001234',
	},
]
